### ISSUE TITLE
keep footer consistent across pages

### ISSUE THREAD

**Issue by derekeder** [datamade/justice-divided#62]
The footer should look the same on all pages

<img width="495" alt="screen shot 2017-05-12 at 3 39 17 pm" src="https://cloud.githubusercontent.com/assets/919583/26016033/047101e0-3729-11e7-855e-137ec7c8750c.png">

<img width="511" alt="screen shot 2017-05-12 at 3 39 26 pm" src="https://cloud.githubusercontent.com/assets/919583/26016037/06c5e5d2-3729-11e7-934c-df44399e527e.png">

**Comment by hancush** [comment]
I pushed some changes to the site for a fix on mobile, perhaps while you were looking. Can you try a force refresh and let me know if you're still having this issue?

**Comment by derekeder** [comment]
yup its good now.
