### ISSUE TITLE
White Hispanic -> Hispanic

### ISSUE THREAD

**Issue by fgregg** [datamade/justice-divided#66]
Let's talk about what "White Hispanic". This is a pretty unusual phrase, so let's figure out why you feel like you need to include it and how we can avoid it.

**Comment by hancush** [comment]
Arrest data differentiates between white and black Hispanic, though it's unclear how. Demographic data is for white, not Hispanic; black only; and Hispanic. DJJ exits use Hispanic.

So really, we need to use White Hispanic for arrests (or combine black and white Hispanic counts – there are less than 20 black Hispanic arrests in each year of our data). Everything else can be "Hispanic." What will be the least confusing for the reader?
