### ISSUE TITLE
stronger bridge between all arrests  charts and chicago map

### ISSUE THREAD

**Issue by fgregg** [datamade/justice-divided#67]
Megan was not able to fully understand what the map was showing. I thin this could be helped with a stronger bridge between the map and the previous section.

"This pattern is worse when you look at arrests for all offenses. In 2014, black youth in Chicago were 1.9 times more likely to be arrested than all youth in Chicago."

Then maybe something like. "While black youth are 1.9 times more likely to be arrested citywide, it's even worse in many neighborhoods.... "

**Comment by hancush** [comment]
Better?

<img width="1205" alt="screen shot 2017-05-15 at 9 09 16 am" src="https://cloud.githubusercontent.com/assets/12176173/26061668/32f21168-394e-11e7-99e4-eb634971bb50.png">

**Comment by fgregg** [comment]
Good, but there's a typo:

While black youth are 1.9 times more likely to be arrested citywide, the disparity is worse **IN** certain neighborhoods. In several of them, black youth make up the smallest share of the population, but the largest share of arrests.

Also, anyway we could we color the 1.9 in like the neigborhood multipliers.
