### ISSUE TITLE
In the marijuana arrest chart, showing disproportionalely maybe show the "proportionate arrests"

### ISSUE THREAD

**Issue by fgregg** [datamade/justice-divided#68]
We are asking them to remember what the proportionate arrests would look like. Might be better not to make that ask.

**Comment by hancush** [comment]
The annotation is supposed to serve this purpose. How's this revision? 

<img width="595" alt="screen shot 2017-05-15 at 8 13 15 am" src="https://cloud.githubusercontent.com/assets/12176173/26059172/615f2106-3946-11e7-8d8b-32936793c090.png">

The main purpose of this chart is to show that the disproportionality we've already demonstrated in several ways is persistent even as fewer arrests are made.

**Comment by hancush** [comment]
(I'm assuming this is the chart you're talking about?)

**Comment by hancush** [comment]
<img width="1171" alt="screen shot 2017-05-15 at 9 55 21 am" src="https://cloud.githubusercontent.com/assets/12176173/26063789/a235c1a4-3954-11e7-91e4-f9ecf9ff10aa.png">

If it's this one, we say that proportionate arrests look like the population. Is showing the population not enough of a reference point to the reader? Would you change the label from population to expected arrests?
