### ISSUE TITLE
couple of totally optional, but might be delightful things

### ISSUE THREAD

**Issue by fgregg** [datamade/justice-divided#69]
1. could the favicon show an imbalanced scale of justice
2. might be fun to embed the myreps instead of linking to that, I believe that @derekeder was looking into doing an iframe version.

**Comment by hancush** [comment]
I can definitely do number one. @derekeder, what about number two?

**Comment by derekeder** [comment]
Let me try and take a crack at this this afternoon.

**Comment by derekeder** [comment]
n/m not doing myreps. closing!
