### ISSUE TITLE
misc feedback from Aya

### ISSUE THREAD

**Issue by derekeder** [datamade/justice-divided#71]
- [x] on mobile, source links are easy to accidentally click on (maybe make them not links and have an appendix page?)
- [x] source link for actual marijuana arrests is cut off on mobile
- [x] source link for all arrests is cut off on mobile
- [x] "then the youth who were arrested" => "then the youth who are arrested"
- [x] mobile map breaks entire site if you drag (using Chrome on Android)
- [ ] ~"this divide" => "this discrepancy"~
- [x] purple text is hard to read on the declining arrests section. maybe use the same green when talking about marijuana above?
- [ ] still using placeholder text on map
- [x] why does the declining arrests chart mention 2012 but then start on 2013?
- [ ] title on chart for declining arrests?
- [x] "as the number of arrests have fallen, the proportion of arrests of black youth have stayed the same"
- [x] numbers in proportions of arrests over time are hard to read
- [ ] ~use consistent labeling on charts. use 'youth' instead of 'kids'~
- [x] annotations are distracting on the proportionality chart. why are 2014 and 2015 called out?
- [x] what 'certain offenses' prevent you from getting federal aid?
- [x] "districts where most youth are black or Latino" - why are we saying Latino instead of Hispanic here?
- [x] "This effect is concentrated in neighborhoods home to more people who are imprisoned. As a consequence, disproportionate minority contact makes whole neighborhoods poorer." opportunity to link to http://chicagosmilliondollarblocks.com ?

**Comment by hancush** [comment]
My mom had the same trouble with accidentally clicking the download links on mobile; I'm removed the href from the chart credits and hid the data download buttons after each chart on mobile. 

I'm not sure what "still using placeholder text on map" means.

Our data doesn't include 2012. I axed the annotations for that chart and added 2012 to the caption instead. I've also reduced the annotations to one on the disproportionality chart.

Checking boxes on other fixes I've completed.
