### ISSUE TITLE
Action labels break across lines

### ISSUE THREAD

**Issue by Mr0grog** [datamade/justice-divided#80]
This situation looks a little weird when first reading it:

![img_2620](https://cloud.githubusercontent.com/assets/74178/26141001/855ebafa-3a8e-11e7-9321-347443110d78.PNG)

You should be able to keep the icon and label together with:

```css
.action { white-space: nowrap; }
```

It might be nice to give the text there a larger `line-height` there, too, so the tops and bottoms of the actions don't touch each other.

**Comment by derekeder** [comment]
good catch! thx @Mr0grog!

**Comment by Mr0grog** [comment]
Always happy to nit-pick ;)
