### ISSUE TITLE
Order of graphs

### ISSUE THREAD

**Issue by easherma** [datamade/justice-divided#85]
This might be subjective, personal preference, but I'd rather see the actual charts on marijuana arrests before the hypothetical. As is, you have the statement "Black youth are arrested more often, even for the same behavior" immediately followed by a chart that appears at first glance to show this is _not_ the case.

It would be groovy if you showed the actual chart and the user could click a button that would shift and animate the graph to what it 'should' look like to compare back and forth instead of a separate hypothetical chart.

**Comment by hancush** [comment]
Thanks for the feedback, @easherma. The content of the Learn tab is fixed for now.
